"""集中调参入口。

这里放策略、走位、踢球和避障的可调参数。数值迁移自当前代码文件,
以后优先在本文件调整参数。
"""

from __future__ import annotations

import math


# ======================================================================
# 踢球力度
# ======================================================================

# Player.kick() 会把力度夹到这个范围内。如果超过范围，因为控制接口不支持，可能会摔倒。
KICK_POWER_MIN = 1.0
KICK_POWER_MAX = 10.0

# 普通进攻 striker 的动态射门力度：离对方球门越远力度越大。
OFFENSIVE_STRIKER_SHOT_POWER_MIN = 4.0
OFFENSIVE_STRIKER_SHOT_POWER_MAX = 8.0
OFFENSIVE_STRIKER_SHOT_POWER_FULL_DISTANCE_M = 6.50

# 我方开球保持独立力度，不跟随普通进攻或防守解围调参。
KICK_POWER_OUR_KICKOFF = 5.0

# 我方中场开球固定一传一接站位。passer 按图片默认在球后下侧准备，
# receiver 按图片默认在我方半场的球后上侧接应；传球点给接应点少量提前量。
OUR_KICKOFF_PASSER_BEHIND_DISTANCE_M = 0.35
OUR_KICKOFF_PASSER_LATERAL_OFFSET_M = 1.35
OUR_KICKOFF_RECEIVER_OWN_HALF_DISTANCE_M = 1.25
OUR_KICKOFF_RECEIVER_LATERAL_OFFSET_M = 2.75
OUR_KICKOFF_PASS_TARGET_FORWARD_BIAS_M = 0.12
OUR_KICKOFF_RECEIVER_FOOT_LATERAL_OFFSET_M = -0.15

OUR_KICKOFF_PASSER_READY_DISTANCE_M = 0.24
OUR_KICKOFF_RECEIVER_READY_DISTANCE_M = 0.34
OUR_KICKOFF_RECEIVER_HEADING_TOLERANCE_RAD = math.radians(28.0)
OUR_KICKOFF_FIELD_MARGIN_M = 0.35
OUR_KICKOFF_CENTER_ORIGIN_TOLERANCE_M = 0.55

OUR_KICKOFF_PASS_POWER = 1.5
OUR_KICKOFF_PASSER_TOUCH_DISTANCE_M = 0.55
OUR_KICKOFF_PASSER_APPROACH_BEHIND_BALL_M = 0.28
OUR_KICKOFF_PASSER_APPROACH_ARRIVE_DISTANCE_M = 0.18
OUR_KICKOFF_PASSER_FINAL_BEHIND_MIN_M = 0.10
OUR_KICKOFF_PASSER_FINAL_LATERAL_TOLERANCE_M = 0.24
OUR_KICKOFF_PASSER_FINAL_HEADING_TOLERANCE_RAD = math.radians(22.0)
OUR_KICKOFF_PASSER_MAX_FINAL_ADJUST_SEC = 0.75
OUR_KICKOFF_PASS_START_CONFIRM_DISTANCE_M = 0.24
OUR_KICKOFF_RECEIVE_RADIUS_M = 0.82
OUR_KICKOFF_RECEIVER_BALL_DISTANCE_M = 0.78
OUR_KICKOFF_RECEIVER_CLOSER_MARGIN_M = 0.12
OUR_KICKOFF_PASS_MIN_FORWARD_PROGRESS_M = 0.18
OUR_KICKOFF_PASS_WRONG_DIRECTION_PROGRESS_M = -0.08
OUR_KICKOFF_PASS_LATERAL_TOLERANCE_M = 0.75
OUR_KICKOFF_PASS_SEVERE_LATERAL_TOLERANCE_M = 1.30
OUR_KICKOFF_OPPONENT_FIRST_DISTANCE_M = 0.62
OUR_KICKOFF_OPPONENT_ARRIVAL_ADVANTAGE_M = 0.20

OUR_KICKOFF_POSITIONING_TIMEOUT_SEC = 6.0
OUR_KICKOFF_PASSING_TIMEOUT_SEC = 5.0
OUR_KICKOFF_RECEIVING_TIMEOUT_SEC = 4.0
OUR_KICKOFF_TOTAL_TIMEOUT_SEC = 12.0


# ======================================================================
# Player 走位控制
# ======================================================================

ARRIVE_DIST = 0.15             # 到达目标点阈值 (m)
MAX_LINEAR = 2.0               # 指令前进速度上限 (m/s)
MAX_ANGULAR = 2.0              # 指令转向速度上限 (rad/s)
LINEAR_GAIN = 1.5              # 平移 P 增益
ANGULAR_GAIN = 2.0             # 转向 P 增益

# 近距全向 / 远距弧线行走使用不同的进入、退出阈值,避免在 1m 附近来回切换。
OMNI_ENTER_DIST = 0.90
OMNI_EXIT_DIST = 1.10

# 远距移动优先边走边转;角差足够大时才进入原地转向,回到较小角差后恢复前进。
TURN_IN_PLACE_ENTER = 0.85
TURN_IN_PLACE_EXIT = 0.55

# 距离到达阈值进入该范围后逐步降低平移速度。
ARRIVAL_BRAKE_DISTANCE_M = 0.35

# 沿规划方向的障碍净空越小,平移速度越低。小于 STOP 时只允许转向。
CLEARANCE_SPEED_STOP_M = 0.05
CLEARANCE_SPEED_FULL_M = 0.65


# ======================================================================
# Offensive striker 追球 / 射门规划
# ======================================================================

OFFENSIVE_STRIKER_KICK_ENTER_M = 2.25
OFFENSIVE_STRIKER_KICK_EXIT_M = 2.75
OFFENSIVE_STRIKER_BEHIND_BALL_DISTANCE_M = 0.35

# 机器人位于球的错误一侧时,先沿球周围的圆弧绕到射门线后方。
OFFENSIVE_STRIKER_CIRCLE_RADIUS_M = 0.65
OFFENSIVE_STRIKER_CIRCLE_STEP_RAD = math.radians(35.0)
# 更早接受当前球后角度并射门，减少反复瞄准和绕球等待。
OFFENSIVE_STRIKER_DIRECT_ENTER_ANGLE_RAD = math.radians(40.0)
OFFENSIVE_STRIKER_DIRECT_EXIT_ANGLE_RAD = math.radians(55.0)
OFFENSIVE_STRIKER_CIRCLE_PROGRESS_RAD = math.radians(5.0)
OFFENSIVE_STRIKER_CIRCLE_TIMEOUT_SEC = 1.5
OFFENSIVE_STRIKER_CIRCLE_FALLBACK_SEC = 0.5

# 对手也贴近球时，不再为了完美球后位后撤，优先低力度朝对方球门破坏球。
OFFENSIVE_STRIKER_DISRUPT_DISTANCE_M = 0.90
OFFENSIVE_STRIKER_DISRUPT_OPPONENT_DISTANCE_M = 1.20
OFFENSIVE_STRIKER_DISRUPT_POWER = 4.0

# 近球但射门角度尚不完美时，用小力度向前推球，避免为了完美球后位反复后撤。
OFFENSIVE_STRIKER_SOFT_DRIBBLE_DISTANCE_M = 0.95
OFFENSIVE_STRIKER_SOFT_DRIBBLE_MAX_ALIGNMENT_RAD = math.radians(115.0)
OFFENSIVE_STRIKER_SOFT_DRIBBLE_POWER = 2.2
OFFENSIVE_STRIKER_SOFT_DRIBBLE_GOAL_MARGIN_M = 2.0

# 射门目标动态调整：正球瞄门，稍偏球向场内推正，极偏角球区不强行调整。
OFFENSIVE_STRIKER_SHOT_STRAIGHT_LATERAL_MARGIN_M = 0.45
OFFENSIVE_STRIKER_SHOT_ADJUST_LATERAL_BAND_M = 1.40
OFFENSIVE_STRIKER_SHOT_ADJUST_FORWARD_DISTANCE_M = 2.20
OFFENSIVE_STRIKER_SHOT_ADJUST_INFIELD_DISTANCE_M = 1.00
OFFENSIVE_STRIKER_SHOT_EXTREME_CORNER_X_M = 2.00
OFFENSIVE_STRIKER_SHOT_EXTREME_TOUCHLINE_MARGIN_M = 0.80
OFFENSIVE_STRIKER_SHOT_FIELD_MARGIN_M = 0.25

# 射门触发动态放宽：普通进攻应更容易大脚，尤其接应人拿到球后
# 直接按进攻 striker 逻辑射门，而不是把固定开球战术继续加长。
OFFENSIVE_STRIKER_FAR_SHOT_GOAL_DISTANCE_M = 6.50
OFFENSIVE_STRIKER_FAR_SHOT_ENTER_ANGLE_RAD = math.radians(55.0)
OFFENSIVE_STRIKER_FAR_SHOT_EXIT_ANGLE_RAD = math.radians(70.0)
OFFENSIVE_STRIKER_RELAXED_SHOT_ENTER_ANGLE_RAD = math.radians(80.0)
OFFENSIVE_STRIKER_RELAXED_SHOT_EXIT_ANGLE_RAD = math.radians(95.0)


# ======================================================================
# Player 技术动作参数：守门 / 支援 
# ======================================================================

GUARD_FACE_BALL = True
GUARD_THREAT_ENTER_X = -1.0
GUARD_THREAT_EXIT_X = -0.7

# 守门员动态门前站位。X 为己方门线向场内的距离，Y 始终夹在门柱内侧。
GOALKEEPER_HOME_X_OFFSET_M = 0.55
GOALKEEPER_BLOCK_X_OFFSET_M = 0.45
GOALKEEPER_TRACK_GAIN_FAR = 0.18
GOALKEEPER_TRACK_GAIN_NEAR = 0.55
GOALKEEPER_TRACK_NEAR_DISTANCE_M = 4.0
GOALKEEPER_MAX_LATERAL_M = 1.0
GOALKEEPER_POST_MARGIN_M = 0.25
GOALKEEPER_TRACK_ARRIVE_M = 0.12

# 独立有限差分球速估计；异常采样只重播种，不用于威胁判断。
GOALKEEPER_BALL_SAMPLE_MIN_SEC = 0.04
GOALKEEPER_BALL_SAMPLE_MAX_SEC = 0.80
GOALKEEPER_BALL_SAMPLE_MAX_JUMP_M = 2.5
GOALKEEPER_BALL_MAX_CREDIBLE_SPEED_MPS = 12.0
GOALKEEPER_BALL_VELOCITY_MAX_AGE_SEC = 0.35

# 快速射门与无可靠速度时的位置威胁。
GOALKEEPER_FAST_BALL_SPEED_MPS = 2.0
GOALKEEPER_GOALWARD_VX_MPS = 0.8
GOALKEEPER_SLOW_BALL_SPEED_MPS = 0.9
GOALKEEPER_SHOT_PROJECTION_MARGIN_M = 0.35
GOALKEEPER_POSITION_THREAT_X_M = -3.5
GOALKEEPER_POSITION_THREAT_LATERAL_M = 2.0
GOALKEEPER_POSITION_THREAT_OPPONENT_DISTANCE_M = 1.5

# 慢球安全出击。进入和退出距离不同，避免在边界反复切换。
GOALKEEPER_CHALLENGE_ENTER_DISTANCE_M = 2.2
GOALKEEPER_CHALLENGE_EXIT_DISTANCE_M = 2.8
GOALKEEPER_CHALLENGE_ADVANTAGE_M = 0.5
GOALKEEPER_CHALLENGE_MAX_X_M = -3.4
GOALKEEPER_CHALLENGE_MAX_LATERAL_M = 2.6
GOALKEEPER_CHALLENGE_TIMEOUT_SEC = 3.0

# 门前解围和状态迟滞。解围目标始终位于球的正 X 前方。
GOALKEEPER_CLEAR_ENTER_DISTANCE_M = 0.65
GOALKEEPER_CLEAR_EXIT_DISTANCE_M = 1.10
GOALKEEPER_CLEAR_APPROACH_DISTANCE_M = 1.45
GOALKEEPER_CLEAR_MIN_HOLD_SEC = 0.45
GOALKEEPER_CLEAR_TIMEOUT_SEC = 1.5
GOALKEEPER_CLEAR_FORWARD_DISTANCE_M = 4.0
GOALKEEPER_CLEAR_LATERAL_DISTANCE_M = 2.2
GOALKEEPER_CLEAR_CENTER_BAND_M = 0.35
GOALKEEPER_CLEAR_FIELD_MARGIN_M = 0.4
GOALKEEPER_CLEAR_POWER = 9.0
GOALKEEPER_MODE_MIN_HOLD_SEC = 0.45
GOALKEEPER_RETURN_ARRIVE_M = 0.25

SUPPORT_DIST_M = 3.0

# ======================================================================
# Normal 阶段策略
# ======================================================================

DEFAULT_GOALKEEPER_ID = 1  # 裁判守门员字段无效时的稳定回退编号

OFFENSIVE_STRIKER_KEEP_DISTANCE_MARGIN_M = 0.3
DEFENSIVE_PRESSER_KEEP_DISTANCE_MARGIN_M = 0.10

FALLEN_COST = 10.0  # 摔倒球员的距离惩罚值(米)

# 双前场普通进攻:搭档围绕球动态接应,并在明显更接近球时临时处理球。
NORMAL_ATTACK_PARTNER_CHALLENGE_DISTANCE_M = 1.4
NORMAL_ATTACK_PARTNER_CLOSER_MARGIN_M = 0.15
NORMAL_ATTACK_SUPPORT_FORWARD_DISTANCE_M = 0.6
NORMAL_ATTACK_SUPPORT_LATERAL_DISTANCE_M = 1.2
NORMAL_ATTACK_REBOUND_FORWARD_DISTANCE_M = 0.85
NORMAL_ATTACK_REBOUND_LATERAL_DISTANCE_M = 0.9
NORMAL_ATTACK_SUPPORT_STRIKER_SPACING_M = 1.0
NORMAL_ATTACK_SUPPORT_TOUCHLINE_ZONE_M = 0.9
NORMAL_ATTACK_SUPPORT_FIELD_MARGIN_M = 0.3
NORMAL_ATTACK_REBOUND_PENALTY_MARGIN_M = 0.5

# 普通比赛攻防态估计。distance_advantage = 对方最近距离 - 我方最近距离。
OPEN_PLAY_ATTACK_DISTANCE_ADVANTAGE_M = 0.45
OPEN_PLAY_DEFENSE_DISTANCE_ADVANTAGE_M = 0.35
OPEN_PLAY_CONTESTED_DISTANCE_BAND_M = 0.15
OPEN_PLAY_MODE_MIN_HOLD_SEC = 1.0

# 对手已经贴近球时保持拼抢模式，避免我方因距离略占优而切入进攻调整。
OPEN_PLAY_OPPONENT_ACTIVE_CHALLENGE_DISTANCE_M = 1.20

# 中场位置带只用于距离证据不充分时辅助判断，不再直接按半场切换攻防。
OPEN_PLAY_CONTESTED_BAND_M = 0.6

# 己方禁区前沿及门前中路属于可立即打断迟滞的危险区域。
OPEN_PLAY_DANGER_X_M = -3.5
OPEN_PLAY_DANGER_LATERAL_MARGIN_M = 0.5
OPEN_PLAY_IMMEDIATE_GOAL_DANGER_DEPTH_M = 1.2

# 保护球员沿球到己方球门的连线站位，并尽量与球保持可用拦截距离。
NORMAL_DEFENSE_PROTECT_DISTANCE_M = 2.0
NORMAL_DEFENSE_GOAL_LINE_CLEARANCE_M = 1.0
NORMAL_DEFENSE_FIELD_MARGIN_M = 0.3

# 防守逼抢者高速直压球点并更早启动低力度抢断。
DEFENSIVE_PRESSER_CHASE_SPEED_MPS = 2.0
DEFENSIVE_PRESSER_TACKLE_POWER = 4.0
DEFENSIVE_PRESSER_TACKLE_ENTER_DISTANCE_M = 0.90
DEFENSIVE_PRESSER_TACKLE_EXIT_DISTANCE_M = 1.10


# ======================================================================
# 丢球恢复
# ======================================================================

BALL_LAST_SEEN_MEMORY_SEC = 3.0
BALL_REACQUIRE_FRAMES = 3
BALL_SEARCH_FACE_TOLERANCE_RAD = 0.20
BALL_SEARCH_YAW_SPEED = 0.60
BALL_SEARCH_SWEEP_SEC = 2.5


# ======================================================================
# M-05 长时间无活动预防
# ======================================================================

INACTIVITY_BALL_DISTANCE_M = 3.0
INACTIVITY_RULE_TIMEOUT_SEC = 10.0
INACTIVITY_PREVENTION_TRIGGER_SEC = 8.0

# 以静止窗口锚点到当前实际 pose 的位移确认有效移动,忽略毫米/厘米级抖动。
INACTIVITY_MOVEMENT_RESET_M = 0.18
INACTIVITY_NUDGE_DISTANCE_M = 0.42
INACTIVITY_GOALKEEPER_NUDGE_DISTANCE_M = 0.30
INACTIVITY_GOALKEEPER_LONGITUDINAL_ADJUSTMENT_M = 0.10
INACTIVITY_NUDGE_ARRIVE_DISTANCE_M = 0.08
INACTIVITY_MIN_TARGET_DISPLACEMENT_M = 0.24
INACTIVITY_NUDGE_TIMEOUT_SEC = 1.8
INACTIVITY_NUDGE_COOLDOWN_SEC = 1.0

# 目标生成只使用动态相对方向；这些参数控制场内余量和远离球的轻微偏置。
INACTIVITY_FIELD_MARGIN_M = 0.35
INACTIVITY_AWAY_FROM_BALL_BIAS = 0.35
INACTIVITY_KICKOFF_HALF_MARGIN_M = 0.10


# ======================================================================
# 开球 / 定位球策略
# ======================================================================

# 开球
KICKOFF_STAGE_M = 2.0
KICKOFF_FRONT_MARGIN = 0.1
KICKOFF_LATERAL_TOL = 0.35

CENTER_LEAVE_DIST_M = 0.15 # 球离开中心点多少距离，认为球已经动了

# 我方界外球。所有目标均由实际发球点和运行时场地尺寸派生。
THROW_IN_BACKFIELD_MAX_X_RATIO = -0.22
THROW_IN_FRONTFIELD_MIN_X_RATIO = 0.22
THROW_IN_TOUCHLINE_TOLERANCE_M = 0.85
THROW_IN_FIELD_MARGIN_M = 0.35
THROW_IN_MIN_FORWARD_PROGRESS_M = 0.45
THROW_IN_MIN_INFIELD_PROGRESS_M = 0.65

THROW_IN_BACKFIELD_FORWARD_OFFSET_M = 2.40
THROW_IN_BACKFIELD_INFIELD_OFFSET_M = 1.70
THROW_IN_MIDFIELD_FORWARD_OFFSET_M = 2.20
THROW_IN_MIDFIELD_INFIELD_OFFSET_M = 1.80
THROW_IN_FRONTFIELD_FORWARD_OFFSET_M = 1.80
THROW_IN_FRONTFIELD_INFIELD_OFFSET_M = 1.60

THROW_IN_KICKER_STAGE_DISTANCE_M = 0.65
THROW_IN_KICKER_STAGE_INFIELD_M = 0.80
THROW_IN_KICKER_READY_DISTANCE_M = 0.24
THROW_IN_KICKER_READY_HEADING_RAD = math.radians(24.0)
THROW_IN_RECEIVER_TRAIL_DISTANCE_M = 0.45
THROW_IN_RECEIVER_READY_DISTANCE_M = 0.50
THROW_IN_REAR_SUPPORT_DISTANCE_M = 1.50
THROW_IN_REAR_SUPPORT_INFIELD_M = 0.45

THROW_IN_SHORT_PASS_POWER_MIN = 3.2
THROW_IN_SHORT_PASS_POWER_MAX = 5.6
THROW_IN_SHORT_PASS_NEAR_DISTANCE_M = 1.50
THROW_IN_SHORT_PASS_FAR_DISTANCE_M = 4.50

THROW_IN_PRESSURE_DISTANCE_M = 1.25
THROW_IN_PRESSURE_LANE_CLEARANCE_M = 0.75
THROW_IN_SHORT_PASS_LANE_CLEARANCE_M = 0.60
THROW_IN_TARGET_OPPONENT_CLEARANCE_M = 0.90
THROW_IN_BACKFIELD_LONG_DISTANCE_M = 5.50
THROW_IN_BACKFIELD_LONG_INFIELD_M = 2.30
THROW_IN_BACKFIELD_LONG_KICK_POWER = 7.5

THROW_IN_OWN_GOAL_FRONT_DEPTH_M = 2.20
THROW_IN_OWN_GOAL_FRONT_LATERAL_MARGIN_M = 0.60

THROW_IN_BALL_START_CONFIRM_DISTANCE_M = 0.25
THROW_IN_BALL_ORIGIN_TOLERANCE_M = 0.18
THROW_IN_WRONG_DIRECTION_PROGRESS_M = -0.08
THROW_IN_PASS_LATERAL_TOLERANCE_M = 0.90
THROW_IN_PASS_SEVERE_LATERAL_TOLERANCE_M = 1.50
THROW_IN_RECEIVE_MIN_PROGRESS_M = 0.65
THROW_IN_RECEIVER_BALL_DISTANCE_M = 0.75
THROW_IN_RECEIVER_CLOSER_MARGIN_M = 0.15
THROW_IN_OPPONENT_BALL_DISTANCE_M = 0.60
THROW_IN_OPPONENT_ARRIVAL_ADVANTAGE_M = 0.25

THROW_IN_POSITIONING_TIMEOUT_SEC = 7.0
THROW_IN_KICKING_TIMEOUT_SEC = 3.0
THROW_IN_PASS_IN_FLIGHT_TIMEOUT_SEC = 4.5
THROW_IN_FOLLOW_UP_TIMEOUT_SEC = 3.0
THROW_IN_TOTAL_TIMEOUT_SEC = 15.0

THROW_IN_FRONT_SHOOT_DISTANCE_M = 4.0
THROW_IN_FOLLOW_UP_FORWARD_DISTANCE_M = 3.0
THROW_IN_FOLLOW_UP_ADVANCE_POWER = 4.5
THROW_IN_FOLLOW_UP_PROGRESS_M = 0.35



# ======================================================================
# 站位 / 避让
# ======================================================================

OPPONENT_RESTART_AVOID_M = 1.6
CIRCLE_MARGIN_M = 0.3


# ======================================================================
# 踢球目标几何
# ======================================================================

GOAL_TARGET_DEPTH_M = 0.25              # 踢球目标点在球门内的深度 (m)

# ======================================================================
# 障碍物几何参数
# ======================================================================

BALL_OBSTACLE_RADIUS = 0.5              # 球的障碍半径 (m)；用于避障计算
OPPONENT_RADIUS = 0.55                  # 对手机器人半径 (m)
TEAMMATE_RADIUS = 0.48                  # 队友机器人半径 (m)
SAFETY_MARGIN = 0.22                    # 通用安全余量 (m)

GOAL_DEPTH = 0.6                        # 球门深度 (m)；用于球门障碍建模
POST_RADIUS = 0.18                      # 门柱半径 (m)
NET_RADIUS = 0.20                       # 球网半径 (m)
NET_STEP = 0.35                         # 球网离散化步长 (m)

START_IGNORE = 0.0                      # 起点忽略半径 (m)；起点附近障碍不参与规划
TARGET_IGNORE = 0.0                     # 终点忽略半径 (m)；终点附近障碍不参与规划

# ======================================================================
# 全局路径规划器 (A* Grid Planner)
# ======================================================================

USE_GLOBAL_PATH_PLANNER = True          # 是否启用全局规划器；False 时回退到局部 VFH
GLOBAL_GRID_RESOLUTION_M = 0.35         # 栅格分辨率 (m/格)；越小路径越精细，但计算量越大
GLOBAL_FIELD_MARGIN_M = 0.25            # 场地边界外扩余量 (m)；确保边界附近路径可行
GLOBAL_OBSTACLE_MARGIN_M = 0.10         # 障碍物膨胀余量 (m)；在障碍半径上额外扩大多少
GLOBAL_PATH_LOOKAHEAD_M = 0.9           # 从规划路径中提取前方多远的路径点 (m)

# ======================================================================
# 局部路径规划器 (VFH Direction Scan)
# ======================================================================

PLAN_LOOKAHEAD = 1.2                    # 前方探测射线长度 (m)；规划器"看"的范围
PLAN_CLEARANCE = 0.35                   # 最小安全余量 (m)；候选方向前方必须大于此值
PLAN_STEP = math.radians(15)            # 候选方向扫描步长 (rad)；越小方向越精细
PLAN_MAX_OFFSET = math.radians(100)     # 最大偏离目标方向的角度 (rad)；扫描范围 ± 该值

# ======================================================================
# 可视化
# ======================================================================

KICK_TARGET_MARK_SIZE_M = 0.18
